name: ci

on:
  push:
    paths-ignore: [ "**.md" ]
  pull_request:
    paths-ignore: [ "**.md" ]

# Cancel older runs on the same branch/PR
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout (with LFS for hooks that read binary files)
        uses: actions/checkout@v5
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

  tests:
    name: tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout (with LFS fixtures)
        uses: actions/checkout@v5
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up PDM + Python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Show tool versions
        run: |
          python -V
          pdm -V

      - name: Install (from lock) + test extras
        run: pdm install --frozen-lockfile -G test,kaggle,vision

      - name: Run pytest
        run: pdm run pytest
        env:
          PYTHONWARNINGS: default

  upload-training-data:
    runs-on: ubuntu-latest
    needs: ["tests"]
    steps:
      - name: Checkout (with LFS fixtures)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up PDM + Python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.13
          cache: true

      - name: Show tool versions
        run: |
          python -V
          pdm -V

      - name: Install (from lock) + extras
        run: pdm install --frozen-lockfile -G kaggle

      - name: Upload dataset
        env:
          KAGGLE_USERNAME: ${{ vars.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: pdm run python -m arc25.kaggle update-training-data -m "${GITHUB_REF_NAME}"
