name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      accelerator:
        description: 'Accelerator type'
        required: true
        type: choice
        options:
          - gpu
          - tpu
          - workbench
          - all
        default: 'gpu'
      push:
        description: 'Push to Artifact Registry'
        required: true
        type: boolean
        default: true
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - 'src/**'
      - 'pyproject.toml'
      - 'pdm.lock'


env:
  GCP_PROJECT_ID: deep-time-358505
  GCP_REGION: europe-west4
  GCP_REPOSITORY: arc-agi
  IMAGE_NAME: arc25

jobs:
  build:
    name: Build ${{ matrix.accelerator }} image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        accelerator: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.accelerator == 'all' && fromJSON('["gpu", "tpu", "workbench"]') || fromJSON(format('["{0}"]', github.event.inputs.accelerator))) || fromJSON('["gpu"]') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
          cache: true

      - name: Prepare build context
        run: |
          mkdir -p docker/buildctxt

      - name: Export dependencies
        run: |
          pdm export --prod --no-hashes -o docker/buildctxt/requirements.txt

      - name: Build wheel
        run: |
          pdm build --no-sdist --dest docker/buildctxt/dist

      - name: Install deployment dependencies
        run: |
          pdm install -G deploy

      - name: Copy data and notebooks to build context
        run: |
          pdm run python -m arc25.deploy prepare-docker-context docker/buildctxt

      - name: Set Dockerfile and image name
        id: docker-config
        run: |
          if [[ "${{ matrix.accelerator }}" == "workbench" ]]; then
            echo "dockerfile=vertex-ai-workbench.dockerfile" >> $GITHUB_OUTPUT
            echo "image_name=arc25-workbench" >> $GITHUB_OUTPUT
          else
            echo "dockerfile=Dockerfile" >> $GITHUB_OUTPUT
            echo "image_name=${{ env.IMAGE_NAME }}" >> $GITHUB_OUTPUT
          fi

      - name: Generate image tags
        id: tags
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="${TIMESTAMP}-${SHORT_SHA}"

          ARTIFACT_REGISTRY_URL="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}"

          IMAGE_NAME="${{ steps.docker-config.outputs.image_name }}"

          if [[ "${{ github.event_name == 'push' || github.event.inputs.push == 'true' }}" == "true" ]]; then
            TAGS="${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}-${{ matrix.accelerator }}"
            TAGS="${TAGS},${ARTIFACT_REGISTRY_URL}/${IMAGE_NAME}:${{ matrix.accelerator }}"
          else
            TAGS="${IMAGE_NAME}:${IMAGE_TAG}-${{ matrix.accelerator }}"
            TAGS="${TAGS},${IMAGE_NAME}:${{ matrix.accelerator }}"
          fi

          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Inspect GitHub OIDC JWT claims
        if: always()
        env:
          AUD: https://iam.googleapis.com/projects/440754660445/locations/global/workloadIdentityPools/github-actions/providers/github-burnanck-only
        run: |
          set -euo pipefail
          tok=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUD" | jq -r .value)

          # decode payload (no signature verification; just for debugging)
          jq -R 'split(".") | .[1] | @base64d | fromjson' <<< "$tok"

      - name: Authenticate to Google Cloud
        if: ${{ github.event_name == 'push' || github.event.inputs.push == 'true' }}
        uses: google-github-actions/auth@v3
        with:
          project_id: deep-time-358505
          workload_identity_provider: 'projects/440754660445/locations/global/workloadIdentityPools/github-actions/providers/github-burnanck-only'

      - name: Configure Docker for Artifact Registry
        if: ${{ github.event_name == 'push' || github.event.inputs.push == 'true' }}
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker/buildctxt
          file: docker/${{ steps.docker-config.outputs.dockerfile }}
          platforms: linux/amd64
          build-args: |
            ACCELERATOR=${{ matrix.accelerator }}
            PYTHON_VERSION=3.13
          push: ${{ github.event_name == 'push' || github.event.inputs.push == 'true' }}
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image info
        run: |
          echo "Built image: ${{ steps.tags.outputs.image_name }}:${{ steps.tags.outputs.image_tag }}-${{ matrix.accelerator }}"
          if [[ "${{ github.event_name == 'push' || github.event.inputs.push == 'true' }}" == "true" ]]; then
            echo "Pushed to: ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}/${{ steps.tags.outputs.image_name }}:${{ steps.tags.outputs.image_tag }}-${{ matrix.accelerator }}"
          fi
