name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'What to build'
        required: true
        type: choice
        options:
          - base
          - training
          - both
        default: 'training'
      accelerator:
        description: 'Accelerator type'
        required: true
        type: choice
        options:
          - gpu
          - tpu
          - both
          - workbench
          - all
        default: 'both'
      push:
        description: 'Push to Artifact Registry'
        required: true
        type: boolean
        default: true
  push:
    tags: ["v*"]     # e.g. v0.3.2
#    branches:
#      - main-disabled
    paths:
      - 'docker/**'
      - 'src/**'
      - 'pyproject.toml'
      - 'pdm.lock'


env:
  GCP_PROJECT_ID: deep-time-358505
  GCP_REGION: europe-west4
  GCP_REPOSITORY: arc-agi

jobs:
  configure:
    name: Configure docker builds
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.config.outputs.image-tag }}
      do-push: ${{ steps.config.outputs.do-push }}
      artifact-registry-url: ${{ steps.config.outputs.artifact-registry-url }}
      image-repo: ${{ steps.config.outputs.image-repo }}
      base-image-accelerators: ${{ steps.config.outputs.base-image-accelerators }}
      training-image-accelerators: ${{ steps.config.outputs.training-image-accelerators }}
    steps:
      - name: Determine docker build configuration
        id: config
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M)
          LONG_SHA="${GITHUB_SHA:-${{ github.sha }}}"
          SHORT_SHA="${LONG_SHA::12}"
          IMAGE_TAG="${TIMESTAMP}-${SHORT_SHA}"
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

          ARTIFACT_REGISTRY_URL="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_REPOSITORY }}"
          echo "artifact-registry-url=${ARTIFACT_REGISTRY_URL}" >> $GITHUB_OUTPUT

          DO_PUSH="${{ github.event_name == 'push' || github.event.inputs.push == 'true' }}"
          echo "do-push=${DO_PUSH}" >> $GITHUB_OUTPUT
          if [[ "${DO_PUSH}"" == "true" ]]; then
            IMAGE_REPO="${ARTIFACT_REGISTRY_URL}/"
          else
            IMAGE_REPO=""
          fi
          echo "image-repo=${IMAGE_REPO}" >> $GITHUB_OUTPUT

          BASE_ACCELS='${{ (github.event.inputs.accelerator == 'all' || github.event.inputs.accelerator == 'both') && '["gpu", "tpu"]' || (github.event.inputs.accelerator == 'workbench' && '[]') || format('["{0}"]', github.event.inputs.accelerator) }}'
          echo "base-image-accelerators=${BASE_ACCELS}" >> $GITHUB_OUTPUT

          TRAINING_ACCELS='${{ github.event_name == 'workflow_dispatch' && ((github.event.inputs.accelerator == 'all' && '["gpu", "tpu", "workbench"]') || (github.event.inputs.accelerator == 'both' && '["gpu", "tpu"]') || format('["{0}"]', github.event.inputs.accelerator)) || '["gpu"]' }}'
          echo "training-image-accelerators=${TRAINING_ACCELS}" >> $GITHUB_OUTPUT


  build-base:
    name: Build base image for ${{ matrix.accelerator }}
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.build_target == 'base' || github.event.inputs.build_target == 'both')
    runs-on: ubuntu-latest
    needs: [configure]
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        # For base images, exclude 'workbench' as it's a training-only variant
        accelerator: ${{fromJSON(needs.configure.outputs.base-image-accelerators) }}
    outputs:
      image-tag: ${{ steps.tags.outputs.image-tag }}
    env:
      IMAGE_NAME: arc25-${{ matrix.accelerator }}-base
      IMAGE_REPO: ${{ needs.configure.outputs.image-repo }}
      IMAGE_TAG: ${{ needs.configure.outputs.image-tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate image tags for base
        id: tags
        run: |
          TAGGED_REF="${IMAGE_REPO}${IMAGE_NAME}:${IMAGE_TAG}"
          LATEST_REF="${IMAGE_REPO}${IMAGE_NAME}:latest"
          REFS="${TAGGED_REF},${LATEST_REF}"
          echo "main-ref=${TAGGED_REF}" >> $GITHUB_OUTPUT
          echo "refs=${REFS}" >> $GITHUB_OUTPUT
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        if: ${{ needs.configure.outputs.do-push }}
        uses: google-github-actions/auth@v3
        with:
          project_id: deep-time-358505
          workload_identity_provider: 'projects/440754660445/locations/global/workloadIdentityPools/github-actions/providers/github-burnanck-only'

      - name: Configure Docker for Artifact Registry
        if: ${{ needs.configure.outputs.do-push }}
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: docker
          file: docker/Dockerfile.base
          platforms: linux/amd64
          build-args: |
            ACCELERATOR=${{ matrix.accelerator }}
            PYTHON_VERSION=3.13
          push: ${{ needs.configure.outputs.do-push }}
          tags: ${{ steps.tags.outputs.refs }}
          cache-from: type=gha,scope=${{ matrix.accelerator }}
          cache-to: type=gha,mode=max,scope=${{ matrix.accelerator }}

      - name: Output image info
        run: |
          echo "Built base image: ${IMAGE_NAME}:${IMAGE_TAG}"
          if [[ "${{ needs.configure.outputs.do-push }}" == "true" ]]; then
            echo "Pushed to: ${{ steps.tags.outputs.main-ref }}"
          fi

  build-training:
    name: Build training image for ${{ matrix.accelerator }}
    needs: [configure, build-base]
    if: |
      always() &&
      (needs.build-base.result == 'success' || needs.build-base.result == 'skipped') &&
      (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && (github.event.inputs.build_target == 'training' || github.event.inputs.build_target == 'both')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        accelerator: ${{fromJSON(needs.configure.outputs.training-image-accelerators) }}
    env:
      IMAGE_NAME: arc25-${{ matrix.accelerator }}
      IMAGE_REPO: ${{ needs.configure.outputs.image-repo }}
      IMAGE_TAG: ${{ needs.configure.outputs.image-tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.13'
          cache: true

      - name: Prepare build context
        run: |
          mkdir -p docker/buildctxt

      - name: Export dependencies
        run: |
          pdm export --prod -G vision -G train --no-hashes -o docker/buildctxt/requirements.txt

      - name: Build wheel
        run: |
          pdm build --no-sdist --dest docker/buildctxt/dist

      - name: Install deployment dependencies
        run: |
          pdm install -G deploy

      - name: Copy data and notebooks to build context
        run: |
          pdm run python -m arc25.deploy prepare-docker-context docker/buildctxt

      - name: Set Dockerfile and generate image tags
        id: config
        run: |
          if [[ "${{ matrix.accelerator }}" == "workbench" ]]; then
            echo "dockerfile=vertex-ai-workbench.dockerfile" >> $GITHUB_OUTPUT
          else
            echo "dockerfile=Dockerfile" >> $GITHUB_OUTPUT
          fi

          # Determine base image tag: use the one just built if base job succeeded, otherwise "latest"
          if [[ "${{ needs.build-base.result }}" == "success" ]]; then
            BASE_IMAGE_TAG="${{ needs.build-base.outputs.image-tag }}"
            echo "Using base image tag from build-base job: ${BASE_IMAGE_TAG}"
          else
            BASE_IMAGE_TAG="latest"
            echo "Using base image tag: ${BASE_IMAGE_TAG}"
          fi
          echo "base-image-tag=${BASE_IMAGE_TAG}" >> $GITHUB_OUTPUT

          TAGGED_REF="${IMAGE_REPO}${IMAGE_NAME}:${IMAGE_TAG}"
          LATEST_REF="${IMAGE_REPO}${IMAGE_NAME}:latest"
          REFS="${TAGGED_REF},${LATEST_REF}"
          echo "main-ref=${TAGGED_REF}" >> $GITHUB_OUTPUT
          echo "refs=${REFS}" >> $GITHUB_OUTPUT

      - name: Inspect GitHub OIDC JWT claims
        if: always()
        env:
          AUD: https://iam.googleapis.com/projects/440754660445/locations/global/workloadIdentityPools/github-actions/providers/github-burnanck-only
        run: |
          set -euo pipefail
          tok=$(curl -sS -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$AUD" | jq -r .value)
          # decode payload (no signature verification; just for debugging)
          jq -R 'split(".") | .[1] | @base64d | fromjson' <<< "$tok"

      - name: Authenticate to Google Cloud
        if: ${{ needs.configure.outputs.do-push }}
        uses: google-github-actions/auth@v3
        with:
          project_id: deep-time-358505
          workload_identity_provider: 'projects/440754660445/locations/global/workloadIdentityPools/github-actions/providers/github-burnanck-only'

      - name: Configure Docker for Artifact Registry
        if: ${{ needs.configure.outputs.do-push }}
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build and push training image
        uses: docker/build-push-action@v5
        with:
          context: docker/buildctxt
          file: docker/${{ steps.config.outputs.dockerfile }}
          platforms: linux/amd64
          build-args: |
            ACCELERATOR=${{ matrix.accelerator }}
            PYTHON_VERSION=3.13
            BASE_IMAGE_REGISTRY=${{ needs.configure.outputs.artifact-registry-url }}
            BASE_IMAGE_TAG=${{ steps.config.outputs.base-image-tag }}
          push: ${{ needs.configure.outputs.do-push }}
          tags: ${{ steps.config.outputs.refs }}
          cache-from: type=gha,scope=${{ matrix.accelerator }}
          cache-to: type=gha,mode=max,scope=${{ matrix.accelerator }}

      - name: Output image info
        run: |
          echo "Built training image: ${IMAGE_NAME}:${IMAGE_TAG}"
          if [[ "${{ needs.configure.outputs.do-push }}" == "true" ]]; then
            echo "Pushed to: ${{ steps.config.outputs.main-ref }}"
          fi
